### ISSUE TITLE
drone-nmap

### ISSUE THREAD

**Issue by 0day1day** [lair-framework/lair#106]
Anyone with this issue with nmap dron import ?

> 2017/12/07 13:38:02 Fatal: Unable to import project. Error dial tcp: lookup https on 127.0.0.53:53: read udp 127.0.0.1:58094->127.0.0.53:53: i/o timeout

**Comment by tomsteele** [comment]
looks like there is probably an issue with how your url is setup. Appears you're trying to lookup a hostname of `https`

**Comment by 0day1day** [comment]
got it :) now i have the

>  2017/12/10 21:44:47 Fatal: Could not unmarshal JSON. Error invalid character '<' looking for beginning of value
on my heroku deployment...

**Comment by jamesbcook** [comment]
can you link a pastebin of the json

**Comment by 0day1day** [comment]
You mean nmap xml file? here we go! https://pastebin.com/FBN3JWaJ

thanks in advance

**Comment by tomsteele** [comment]
@0day1day The heroku deployment doesn't start up the Lair API server which is what the drones use to import data. It's just a way to poke around the Meteor app. https://github.com/ryhanson/lair-docker is a good way to get up and running quickly and you will have a working API there :)

**Comment by 0day1day** [comment]
that's what I was thinking, try with docker, thanks!

**Comment by ilyaglow** [comment]
Actually, you can import from drones with heroku too, but you should start api server by yourself. You could run it with env var`MONGO_URL` pointed to heroku’s generated mongolab db from the very same host as your nmap drone. Although, I wouldn’t recommend heroku deployment for a heavy/production usage, because mongolab free tier will become a bottleneck at some point.

**Comment by 0day1day** [comment]
thanks @ilyaglow i will try! :)
